[package]
name = "lyra"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>", "est31 <MTest31@outlook.com>"]
license = "MIT/Apache-2.0"

[dependencies]
fftw = "0.4.0"

[dev-dependencies]
hound = "3.4.0"
